bundler_args: --without yard guard metrics benchmarks
before_install:
  - gem install bundler --pre
branches:
  only:
    - /^release-.*$/
script: "bundle exec rake spec"
matrix:
  allow_failures:
    - rvm: ree
  include:
    - rvm: 1.8.7
      env: "GIT_BRANCH=release-1.2 WITH_JSON=yajl-ruby"
    - rvm: 1.9.2
      env: "GIT_BRANCH=release-1.2 WITH_JSON=yajl-ruby"
    - rvm: 1.9.3
      env: "GIT_BRANCH=release-1.2 WITH_JSON=yajl-ruby"
    - rvm: 2.0.0
      env: "GIT_BRANCH=release-1.2 WITH_JSON=yajl-ruby"
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head
  - rbx-18mode
  - rbx-19mode
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - ree
env:
  matrix:
    - "GIT_BRANCH=release-1.2 WITH_JSON=json"
notifications:
  email:
    - dan.kubb@gmail.com
notifications:
  irc: "irc.freenode.org#datamapper"
